Allow clickaway events to be handled
pepsico-ecommerce/crunch_berry pull request #28
Opened 2022-06-21 23:13 UTC by kellyfelkins

These changes allow CrunchBerry.Modal clients to assign a target for the close event that
occurs when clicking away from a modal. Prior to this change, you could launch modals without 
a `return_to`, and if you clicked away from those modals, the `handle_event("close"` would attempt
to `push_patch` to assigns.return_to, causing an exception.

I wanted to add tests for this specific exception but did not find a normal way to test modal interactions. I settled
on creating a small phoenix app with tests for the modal. The app is included in the project under ./crunch_berry_test_app. To run the tests, you cd into that directory and `mix test`. Ultimately I hope we shift these tests into their proper home in `crunch_berry/test`.

2022-06-22 12:43 UTC, mphfish requested changes
The code changes look good.

Instead of adding a Phoenix app, we should be able to use [live_isolated/3](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#live_isolated/3) in order to test the component outside of a rendered process tree.

2022-06-22 16:17 UTC, kellyfelkins commented
> The code changes look good.
> 
> Instead of adding a Phoenix app, we should be able to use [live_isolated/3](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#live_isolated/3) in order to test the component outside of a rendered process tree.

I'm having trouble using live_isolated in crunch_berry. I think the issue is that crunch_berry is not a liveview app.

I'm out of my depth here. 

```
(ArgumentError) cannot invoke handle_params/3 on CrunchBerry.Components.ModalTest.SalesLive because it is not mounted nor accessed through the router live/3 macro
```

That's the current error I'm seeing when I try to use live_isolated.

2022-06-24 14:48 UTC, Ch4s3 commented
looks like [live_isolated/3](https://github.com/phoenixframework/phoenix_live_view/blob/766b0f4335b9e12c728329054aadd17473bc2fcb/lib/phoenix_live_view/test/live_view_test.ex#L263) requires an endpoint

2022-06-24 17:30 UTC, kellyfelkins commented
> looks like [live_isolated/3](https://github.com/phoenixframework/phoenix_live_view/blob/766b0f4335b9e12c728329054aadd17473bc2fcb/lib/phoenix_live_view/test/live_view_test.ex#L263) requires an endpoint

Please take a look at [add_interaction_tests_for_modal](https://github.com/pepsico-ecommerce/crunch_berry/tree/add_interaction_tests_for_modal)

Here I created a simple test to exercise existing close button feature using `live_isolated`.

https://github.com/pepsico-ecommerce/crunch_berry/blob/add_interaction_tests_for_modal/test/components/modal_test.exs#L55-L100

The test does a `use CrunchBerry.ComponentCase`, and ComponentCase includes an endpoint.

The test successfully loads the liveview with live_isolated. It fails when clicking the close 'x' with this error:

```
** (ArgumentError) cannot invoke handle_params/3 on CrunchBerry.Components.ModalTest.LiveViewFixture because it is not mounted nor accessed through the router live/3 macro
```

I looked at the phoenix_live_view repo. The test suite includes uses of `live_isolated/3` and uses of `live/2`. Because the test is attempting to do a redirect I believe we will need a router and to start the liveview with `live/2`.

I previously tried using phoenix_live_view tests for examples. After a couple of hours I was still seeing test setup issues and decided I needed another approach. However, another set of eyes might solve this quickly. If we can get this simple test working I can run with it.

2022-06-28 15:27 UTC, mphfish approved these changes

2022-06-28 15:39 UTC, Ch4s3 approved these changes

2022-06-28 15:39 UTC, merged